USE OlistWh;

-- KPI 1 – Total Revenue
-- Definition
-- Total revenue generated from delivered order items (excluding freight).

-- KPI: Total Revenue

SELECT
    SUM(price) AS total_revenue
FROM FactSales;

-- KPI 2 – Average Order Value (AOV)
-- Definition
-- Average revenue generated per order.

-- KPI: Average Order Value

SELECT
    SUM(price) / COUNT(DISTINCT order_id) AS average_order_value
FROM FactSales;

-- KPI 3 – Orders per Month
-- Definition
-- Number of orders placed each month.

-- KPI: Orders per Month

SELECT
    d.year_number,
    d.month_number,
    d.month_name,
    COUNT(DISTINCT f.order_id) AS total_orders
FROM FactSales f
JOIN DimDate d
    ON f.date_key = d.date_key
GROUP BY
    d.year_number,
    d.month_number,
    d.month_name
ORDER BY
    d.year_number,
    d.month_number;

-- KPI 4 – Revenue by Product Category
-- Definition
-- Revenue generated by each product category.

-- KPI: Revenue by Product Category

SELECT
    p.category_name,
    SUM(f.price) AS total_revenue
FROM FactSales f
JOIN DimProduct p
    ON f.product_key = p.product_key
GROUP BY
    p.category_name
ORDER BY
    total_revenue DESC;


-- KPI 5 – Orders by Product Category
-- Definition
-- Number of order items sold per category.

-- KPI: Orders by Product Category

SELECT
    p.category_name,
    COUNT(*) AS total_orders
FROM FactSales f
JOIN DimProduct p
    ON f.product_key = p.product_key
GROUP BY
    p.category_name
ORDER BY
    total_orders DESC;

-- KPI 6 – Revenue by Customer State
-- Definition
-- Revenue generated by customers from each state.

-- KPI: Revenue by State

SELECT
    c.customer_state,
    SUM(f.price) AS total_revenue
FROM FactSales f
JOIN DimCustomer c
    ON f.customer_key = c.customer_key
GROUP BY
    c.customer_state
ORDER BY
    total_revenue DESC;

-- KPI 7 – Revenue by Seller
-- Definition
-- Revenue generated by each seller.

-- KPI: Revenue by Seller

SELECT
    s.seller_id,
    SUM(f.price) AS total_revenue
FROM FactSales f
JOIN DimSeller s
    ON f.seller_key = s.seller_key
GROUP BY
    s.seller_id
ORDER BY
    total_revenue DESC;

-- KPI 8 – Average Delivery Time
-- Definition
-- Average number of days between purchase and delivery.

-- KPI: Average Delivery Time

SELECT
    AVG(delivery_days) AS average_delivery_days
FROM FactSales;

-- KPI 9 – Late Deliveries
-- Definition
-- Number and percentage of late deliveries.

-- KPI: Late Deliveries

SELECT
    COUNT(DISTINCT CASE
        WHEN late_delivery_flag = 1
        THEN order_id
    END) AS late_orders,

    COUNT(DISTINCT order_id) AS total_orders,

    CAST(
        100.0 *
        COUNT(DISTINCT CASE
            WHEN late_delivery_flag = 1
            THEN order_id
        END)
        /
        COUNT(DISTINCT order_id)
        AS DECIMAL(5,2)
    ) AS late_delivery_rate
FROM FactSales;

-- KPI 10 – Customers by State
-- Definition
-- Number of unique customers in each state.

-- KPI: Customers by State

SELECT
    customer_state,
    COUNT(*) AS total_customers
FROM DimCustomer
GROUP BY
    customer_state
ORDER BY
    total_customers DESC;

-- KPI 11 - Repeat Customers
-- Definition:
-- Customers (customer_unique_id) who placed more than one order.

SELECT
    c.customer_unique_id,
    COUNT(DISTINCT f.order_id) AS total_orders
FROM FactSales f
JOIN DimCustomer c
    ON f.customer_key = c.customer_key
GROUP BY
    c.customer_unique_id
HAVING COUNT(DISTINCT f.order_id) > 1
ORDER BY
    total_orders DESC;



